apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: scienceviddb-web
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cloudsql-instances: "regal-scholar-453620-r7:us-central1:scienceviddb-db"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/timeout: "300s"
    spec:
      serviceAccountName: scienceviddb-web@regal-scholar-453620-r7.iam.gserviceaccount.com
      containerConcurrency: 80
      containers:
      - image: gcr.io/regal-scholar-453620-r7/scienceviddb-web:latest
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: USE_SECRETS_MANAGER
          value: "true"
        - name: GOOGLE_CLOUD_PROJECT
          value: "regal-scholar-453620-r7"
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 3000

