apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: scienceviddb-ingestion
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:REGION:INSTANCE"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/timeout: "3600s"
    spec:
      serviceAccountName: scienceviddb-ingestion@regal-scholar-453620-r7.iam.gserviceaccount.com
      containerConcurrency: 10
      containers:
      - image: gcr.io/regal-scholar-453620-r7/scienceviddb-ingestion:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: USE_SECRETS_MANAGER
          value: "true"
        - name: GOOGLE_CLOUD_PROJECT
          value: "regal-scholar-453620-r7"
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "2000m"
            memory: "2Gi"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080

